### ISSUE TITLE
Reset to initial state

### ISSUE THREAD

**Issue by Wargadji** [InfiniteXyy/zoov#4]
Greetings!
How can I reset the state?

I tried 2 options but none of them work
```
const INITIAL_STATE = {...}

const store = defineModule(INITIAL_STATE)
   .actions({
      reset: function () {
         return INITIAL_STATE;
      },
      // and
      reset: function (draft) {
         draft = INITIAL_STATE;
      },
   })
   .build();
```

**Comment by InfiniteXyy** [comment]
Hi, thank you for your feedback!

**How**
You can use `Object.assign` to reset state
```ts
// almost same as https://stackoverflow.com/questions/72025169/how-to-reset-one-of-data-in-pinia-state
 .actions({
    add: (draft, payload: number = 1) => (draft.count += payload),
    setInput: (draft, input: string) => (draft.deep.input = input),
    reset: (draft) => Object.assign(draft, INITIAL_STATE),
  })
```

Another way is to wrap your state in a state object, but a little unreadable
```ts
defineModule({ state: INITIAL_STATE };

reset(draft) { draft.state = INITIAL_STATE; }
```

Or use the internal `$reset` action (if you update to ^0.4.0)
```ts
const { $reset } = useActions()
```
**Why**
Because `zoov` track state changes in the object level, only property changes (or deeper property changes) can cause an update event. You can not just assign assign a new value to an object. And the return value of action is always ignored.

**Comment by InfiniteXyy** [comment]
after v0.4.0, you can use `actions.$reset` to reset your state

**Comment by Wargadji** [comment]
@InfiniteXyy 
Oh! Thanks, this works for me! :)
And also thanks for the separate ```$reset``` action!
