### ISSUE TITLE
How to access actions in persist middleware

### ISSUE THREAD

**Issue by dih7** [InfiniteXyy/zoov#9]
Hello, 

I've recently been migrating to zoov from vanilla Zustand, and I've been using the `onRehydrateStorage` function in the persist middleware to load some initial stuff when the app is loaded.

Is it possible to access getActions in middleware? I couldn't find an example doing this. I can access the store and the state in it, but not the actions.

e.g. for middleware:

```
  .middleware((store) =>
    persist(store, {
      name: 'app',
      onRehydrateStorage: () => async (store) => {
        console.log('rehydrate', { store }); // I'd like to access it here
      },
    })
  )
```

Thanks!

**Comment by InfiniteXyy** [comment]
Sorry, I did some investigation. And then I found `zoov` does not support your requirement by design, The `GetActions` is only available after all middleware are loaded, (`zoov` actions is based on the `zustand` `redux` middleware)

If we want to load actions inside a middleware, it may cause `maximum call stack size`

So one workaround is to add this `setTimeout` callback to call your action. The keypoint is we cannot getActions **synchronously** in a middleware, we have to wait for the initialization
 
```ts
const YourModule = defineModule({})
  .middleware((store) =>
    persist(store, {
      name: 'app',
      onRehydrateStorage: () => async (store) => {
        console.log('rehydrate', { store }); // I'd like to access it here
        setTimeout(() => {
            YourModule.getActions().dosomething()
        })
      },
    })
  )
```

Hope this workaround helps you solve your problem

**Comment by dih7** [comment]
I thought that might be the case.

The workaround works perfectly, thanks!
